server:
  port: 1234

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///e_streaming_system
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.voltlink: debug

